services:
  worker:
    build: 
      context: ..
      dockerfile: worker/Dockerfile.worker
    container_name: worker
    env_file: ../../.env
    network_mode: "host"
    hostname: datanode_1
    volumes:
      - datanode_data:/home/hadoop/hdfs/datanode
  node-exporter-worker:
    image: prom/node-exporter
    network_mode: service:worker


volumes:
  datanode_data: