services:

  worker:

    build: 
      context: ..
      dockerfile: worker/Dockerfile.worker
    container_name: worker
    env_file: ../.env
    network_mode: "host"
  node-exporter-worker:

    image: prom/node-exporter

    network_mode: service:worker