
services:

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana-hadoop
    restart: unless-stopped
    environment:
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel,alexanderzobnin-zabbix-app
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    networks:
      - cluster-network


  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb-hadoop
    ports:
      - "3306:3306"
    volumes:
      - .:/code
    environment:
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - cluster-network

  hadoop:
    build: .
    container_name: app
    restart: unless-stopped
    volumes:
      - cluster_data:/home/hadoop
      - etc_data:/etc/hadoop
      - var_data:/var/hadoop
    networks:
      - cluster-network  


networks:
  - cluster-network:
      driver: bridge

volumes:
  grafana_storage:
  cluster_data:
  etc_data:
  var_data:
