FROM hadoop-base

COPY  /scripts /usr/local/bin
COPY jmx /opt/jmx

USER root

RUN chmod +x /usr/local/bin/master-entrypoint.sh && \
    mkdir -p /home/hadoop/hadoop/hdfs/namenode \
             /home/hadoop/hadoop/hdfs/datanode && \
    chown -R hadoop:hadoop /home/hadoop/hadoop/hdfs

USER hadoop

ENTRYPOINT ["/usr/local/bin/master-entrypoint.sh"]
