

services:

  master:
    
    build:
      context: ..
      dockerfile: master/Dockerfile.master
    hostname: master
    container_name: hadoop-master
    network_mode: "host"
    env_file: ../../.env

  prometheus:

    image: prom/prometheus

    container_name: prometheus

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    network_mode: "host"

  grafana:

    image: grafana/grafana

    container_name: grafana

    ports:

      - "3000:3000"

    volumes:

      - grafana:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/files:/var/lib/grafana/files

    depends_on:

      - prometheus

    network_mode: "host"

  node-exporter-master:

    image: prom/node-exporter

    container_name: exporter-master

    network_mode: service:master




volumes:

  grafana:

networks:
  hadoop-net:
    driver: bridge